--- 
abstract: A framework for function signatures in Moose
author: 
  - Anders Nor Berle <berle@cpan.org>
build_requires: 
  Test::Exception: 0.27
  Test::More: 0.72
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Signature-Function
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0.50
  Scalar::Util: 1.19
version: 0.00_04
